name: Gradle Precommit
on:
  workflow_dispatch
 
jobs:
  precommit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] 
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Run Gradle
        run: |
          ./gradlew :server:test --max-workers 2 -x internalClusterTest
